# Generated by Django 4.2.16 on 2024-09-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('windSpeed', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('pressure', models.FloatField()),
                ('feelsLike', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('cloud', models.FloatField()),
                ('windChill', models.FloatField()),
                ('heatIndex', models.FloatField()),
                ('dewPoint', models.FloatField()),
                ('visibility', models.FloatField()),
                ('uv', models.FloatField()),
                ('gust', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isExtreme', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertMessage', models.CharField(max_length=255)),
                ('alertType', models.CharField(max_length=100)),
                ('triggeredAt', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
    ]
