# Generated by Django 4.2.16 on 2024-09-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_weatherinfo_weatheralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='icon',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='windDir',
            field=models.CharField(default='WNW', max_length=100),
            preserve_default=False,
        ),
    ]
