# Generated by Django 4.2.16 on 2024-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherinfo_icon_weatherinfo_winddir'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='last_updated',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
