# Generated by Django 4.2.16 on 2024-09-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weatherinfo_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='last_updated',
            new_name='lastUpdated',
        ),
    ]
