# Generated by Django 4.2.16 on 2024-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_rename_last_updated_weatherinfo_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='lastUpdated',
            field=models.CharField(max_length=15),
        ),
    ]
