# Generated by Django 4.2.16 on 2024-09-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_weatherinfo_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='pune', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
